"""Add school and area to logs

Revision ID: 0012af7f3b6e
Revises: 54a2929c79e5
Create Date: 2025-11-29 12:29:50.941368

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0012af7f3b6e'
down_revision: Union[str, Sequence[str], None] = '54a2929c79e5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('update_logs', sa.Column('school_name', sa.String(), nullable=True))
    op.add_column('update_logs', sa.Column('area_name', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('update_logs', 'area_name')
    op.drop_column('update_logs', 'school_name')
    # ### end Alembic commands ###
