"""remove enum from asset

Revision ID: a0f4b3de8207
Revises: e17d0ea3e93c
Create Date: 2025-11-30 22:17:13.796728

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a0f4b3de8207'
down_revision: Union[str, Sequence[str], None] = 'e17d0ea3e93c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('assets', 'placement',
               existing_type=postgresql.ENUM('INDOOR', 'OUTDOOR', name='assetplacement'),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('assets', 'status',
               existing_type=postgresql.ENUM('BERFUNGSI', 'TERKENDALA', 'PERBAIKAN', 'RUSAK', 'DIHAPUSKAN', name='assetstatus'),
               type_=sa.String(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('assets', 'status',
               existing_type=sa.String(),
               type_=postgresql.ENUM('BERFUNGSI', 'TERKENDALA', 'PERBAIKAN', 'RUSAK', 'DIHAPUSKAN', name='assetstatus'),
               existing_nullable=False)
    op.alter_column('assets', 'placement',
               existing_type=sa.String(),
               type_=postgresql.ENUM('INDOOR', 'OUTDOOR', name='assetplacement'),
               existing_nullable=True)
    # ### end Alembic commands ###
