"""add master options table

Revision ID: e17d0ea3e93c
Revises: f195c9087cc0
Create Date: 2025-11-30 16:06:33.103691

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e17d0ea3e93c'
down_revision: Union[str, Sequence[str], None] = 'f195c9087cc0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('master_options',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('label', sa.String(), nullable=False),
    sa.Column('parent_code', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_master_options_category'), 'master_options', ['category'], unique=False)
    op.create_index(op.f('ix_master_options_code'), 'master_options', ['code'], unique=False)
    op.create_index(op.f('ix_master_options_id'), 'master_options', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_master_options_id'), table_name='master_options')
    op.drop_index(op.f('ix_master_options_code'), table_name='master_options')
    op.drop_index(op.f('ix_master_options_category'), table_name='master_options')
    op.drop_table('master_options')
    # ### end Alembic commands ###
