"""Add production year to service history

Revision ID: f195c9087cc0
Revises: 0012af7f3b6e
Create Date: 2025-11-29 13:39:40.828255

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f195c9087cc0'
down_revision: Union[str, Sequence[str], None] = '0012af7f3b6e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('service_histories', sa.Column('production_year', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('service_histories', 'production_year')
    # ### end Alembic commands ###
